### ISSUE TITLE
Parameter no set -p

### ISSUE THREAD

**Issue by pqks** [raylee/tldr#35]
When i type: `tldr -p` I have the next output:

`/home/pcwork/bin/tldr: 285: /home/pcwork/bin/tldr: 1: parameter not set`

**Comment by raylee** [comment]
Hello! The -p option requires a parameter for the specific platform you want to use instead of the autodetected one. So if you want to override what tldr decides, you can use 

`tldr -p os`

Where `os` is one of `linux`, `windows`, `sunos`, `osx`, or `common`.

You should never need to use the parameter unless you are writing new tldr pages for a different platform, or you are looking for docs on a command that isn't on your platform.

I'll add error handling to that path to catch these cases.
